services:
  app:
    image: nguyenhoanghieu1510/cafe-app:latest
    container_name: cafe-spring-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/CafeManagement?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=hieudeptrai
      - spring.jpa.hibernate.ddl-auto=validate
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: cafe-mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hieudeptrai
      - MYSQL_DATABASE=CafeManagement
      # THÊM 2 DÒNG NÀY: Buộc MySQL dùng UTF-8
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data: